Vagrant.configure("2") do |config|
  # Define environment
  vmname = "dev"
  # Define the VM
  config.vm.define "vmname" do |vmname|
    vmname.vm.box = "generic/ubuntu2204"
    vmname.vm.network "private_network", ip: "192.168.56.12"
    vmname.vm.hostname = "vmname"

    vmname.vm.provider "virtualbox" do |vb|
      vb.name = "vmname"
      vb.cpus = 2
      vb.memory = "2048"
    end

    # Run shell commands
    vmname.vm.provision "shell", inline: <<-SHELL
      # Set password for root account and allow SSH
      echo "root:123" | chpasswd
      sed -i 's/^#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl reload sshd

      # Append the following content to /etc/hosts for accessing machines by HOSTNAME
      cat >>/etc/hosts<<EOF
      192.168.56.10 prod
      192.168.56.11 stag
      192.168.56.12 dev
      192.168.56.50 gitlab
      192.168.56.60 jenkins
EOF
    SHELL
  end

  # Define environment
  vmname = "stag"
  # Define the VM
  config.vm.define "vmname" do |vmname|
    vmname.vm.box = "generic/ubuntu2204"
    vmname.vm.network "private_network", ip: "192.168.56.11"
    vmname.vm.hostname = "vmname"

    vmname.vm.provider "virtualbox" do |vb|
      vb.name = "vmname"
      vb.cpus = 2
      vb.memory = "2048"
    end

    # Run shell commands
    vmname.vm.provision "shell", inline: <<-SHELL
      # Set password for root account and allow SSH
      echo "root:123" | chpasswd
      sed -i 's/^#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl reload sshd

      # Append the following content to /etc/hosts for accessing machines by HOSTNAME
      cat >>/etc/hosts<<EOF
      192.168.56.10 prod
      192.168.56.11 stag
      192.168.56.12 dev
      192.168.56.50 gitlab
      192.168.56.60 jenkins
EOF
    SHELL
  end

  # Define environment
  vmname = "prod"
  # Define the VM
  config.vm.define "vmname" do |vmname|
    vmname.vm.box = "generic/ubuntu2204"
    vmname.vm.network "private_network", ip: "192.168.56.10"
    vmname.vm.hostname = "vmname"

    vmname.vm.provider "virtualbox" do |vb|
      vb.name = "vmname"
      vb.cpus = 2
      vb.memory = "2048"
    end

    # Run shell commands
    vmname.vm.provision "shell", inline: <<-SHELL
      # Set password for root account and allow SSH
      echo "root:123" | chpasswd
      sed -i 's/^#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl reload sshd

      # Append the following content to /etc/hosts for accessing machines by HOSTNAME
      cat >>/etc/hosts<<EOF
      192.168.56.10 prod
      192.168.56.11 stag
      192.168.56.12 dev
      192.168.56.50 gitlab
      192.168.56.60 jenkins
EOF
    SHELL
  end

  # Define environment
  vmname = "gitlab"
  # Define the VM
  config.vm.define "vmname" do |vmname|
    vmname.vm.box = "generic/ubuntu2204"
    vmname.vm.network "private_network", ip: "192.168.56.50"
    vmname.vm.hostname = "vmname"

    vmname.vm.provider "virtualbox" do |vb|
      vb.name = "vmname"
      vb.cpus = 2
      vb.memory = "2048"
    end

    # Run shell commands
    vmname.vm.provision "shell", inline: <<-SHELL
      # Set password for root account and allow SSH
      echo "root:123" | chpasswd
      sed -i 's/^#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl reload sshd

      # Append the following content to /etc/hosts for accessing machines by HOSTNAME
      cat >>/etc/hosts<<EOF
      192.168.56.10 prod
      192.168.56.11 stag
      192.168.56.12 dev
      192.168.56.50 gitlab
      192.168.56.60 jenkins
EOF
    SHELL
    # Run Ansible playbook
    gitlab.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/playbook.yml"
      ansible.inventory_path = "ansible/inventory"
    end
  end

  # Define environment
  vmname = "jenkins"
  # Define the VM
  config.vm.define "vmname" do |vmname|
    vmname.vm.box = "generic/ubuntu2204"
    vmname.vm.network "private_network", ip: "192.168.56.60"
    vmname.vm.hostname = "vmname"

    vmname.vm.provider "virtualbox" do |vb|
      vb.name = "vmname"
      vb.cpus = 2
      vb.memory = "2048"
    end

    # Run shell commands
    vmname.vm.provision "shell", inline: <<-SHELL
      # Set password for root account and allow SSH
      echo "root:123" | chpasswd
      sed -i 's/^#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl reload sshd

      # Append the following content to /etc/hosts for accessing machines by HOSTNAME
      cat >>/etc/hosts<<EOF
      192.168.56.10 prod
      192.168.56.11 stag
      192.168.56.12 dev
      192.168.56.50 gitlab
      192.168.56.60 jenkins
EOF
    SHELL
  end
end