---
- hosts: gitlab
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name:
          - curl
          - openssh-server
          - ca-certificates
          - tzdata
        state: present
        update_cache: yes
      vars:
        packages:
          - ca-certificates
          - curl
          - openssh-server
          - postfix

    - name: Add GitLab repository key
      apt_key:
        url: https://packages.gitlab.com/gpg.key
        state: present

    - name: Add GitLab repository
      apt_repository:
        repo: 'deb https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ focal main'
        state: present

    - name: Install GitLab
      apt:
        name: gitlab-ce
        state: present
