---
- hosts: gitlab
  become: yes
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-requests
        state: present
        update_cache: yes

    - name: Add Docker official GPG key
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add the Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Pull the latest GitLab CE Docker image
      ansible.builtin.docker_image:
        name: gitlab/gitlab-ce
        tag: latest
        source: pull

    - name: Create directories to store GitLab configuration and data
      ansible.builtin.file:
        path: /srv/gitlab/{{ item }}
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - config
        - logs
        - data

    - name: Run the GitLab CE Docker container
      ansible.builtin.docker_container:
        name: gitlab
        image: gitlab/gitlab-ce:latest
        state: started
        restart_policy: always
        hostname: 192.168.56.50
        published_ports:
          - "443:443"
          - "80:80"
        volumes:
          - /srv/gitlab/config:/etc/gitlab
          - /srv/gitlab/logs:/var/log/gitlab
          - /srv/gitlab/data:/var/opt/gitlab